### PR TITLE
feat: cookie authentication

### PR DESCRIPTION
**Pull request by rescribet**
- [x] Implements #512 
- [x] Include updated JS assets (`pnpm build-server`) for the client-side Cookie implementation https://github.com/atomicdata-dev/atomic-data-browser/pull/246
- [x] Update Contribute.md, link to issue number
- [x] Resolved pending review comments

### CODE REVIEW

**Comment by joepio** [comment]
Custom checklist for PR (for some reason the template is missing in this PR):

- [ ] Include updated JS assets (`pnpm build-server`) for the client-side Cookie implementation
- [ ] Update Contribute.md, link to issue number

**Comment by rescribet** [comment]
Updated the test bundle, here the items was already added to the changelog too.

**Comment by joepio** [comment]
Test fails because the `expected` and `actual` images are different, because one is `Atomic Data` and the other `Atomic Data Rust`

https://github.com/atomicdata-dev/atomic-data-rust/actions/runs/3329831746/jobs/5507547427#step:11:178

**Comment by rescribet** [comment]
Yes, I forgot to update the test config file here

**Pull request merged**
